# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Philippe KUBLER
tagline:          'Webmaster Editorial'
description:      'Stratégie de Contenu et intégrateur web'
url:              https://philippekubler.github.io
baseurl:          /

author:
  name:           'Made by Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
