# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Philippe KUBLER
tagline:          'Webmaster Editorial'
description:      'Consultant en stratégie de contenu et intégrateur web : HTML5, CSS, JS (NodeJS le w-e) Wordpress, Drupal et Episerver. Mobile-first et Client-oriented. Accroc à son arduino.'
url:              https://philippekubler.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
